name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        name: ruff isort
        with:
          args: check --select I
      - uses: astral-sh/ruff-action@v3
        name: ruff format
        with:
          args: format --check
